//! Shared codegen for `iwssim` / `iwssim-gpu` filter-tap constants.
//!
//! Both crates' `build.rs` import [`emit_filters_rs`] and write the
//! result into their own `OUT_DIR/filters.rs`. Each crate then exposes
//! the constants via `include!(concat!(env!("OUT_DIR"), "/filters.rs"))`
//! from a local `crate::filters` module. This keeps the cube-macro
//! resolution path (`crate::filters::BINOM5` etc.) intact in
//! `iwssim-gpu` while reducing the codegen to a single source of
//! truth.
//!
//! Two filters are baked in:
//!
//! 1. **`BINOM5`** — pyrtools `binom5` (`sqrt(2) * [1,4,6,4,1]/16`),
//!    used in the separable Burt-Adelson Laplacian pyramid build and
//!    expand. The `sqrt(2)` factor is pyrtools' convention; matters
//!    for byte-for-byte parity with `pyrtools.pyramids.LaplacianPyramid`.
//! 2. **`SSIM_WIN_11`** — `fspecial('gaussian', 11, 1.5)` reduced to
//!    a 1D separable kernel (the same Gaussian, separable application
//!    yields the same 2D result thanks to outer-product factorization).
//!
//! And one constant table:
//!
//! 3. **`SCALE_WEIGHTS`** — per-scale MS-SSIM combination weights
//!    (β in eq 47 of Wang & Li 2011) verbatim from `iwssim.m` /
//!    `IW_SSIM_PyTorch.py`.

use std::io::{self, Write};

/// Pyrtools `binom5` taps (`sqrt(2) * [1,4,6,4,1] / 16`).
///
/// The `sqrt(2)` factor is intentional: it's how pyrtools preserves
/// L2 norm through pyramid build/expand. Without it the LP coefficients
/// differ from the published Python implementation by a scale factor
/// at every level, which would silently break parity.
pub fn binom5_taps() -> [f64; 5] {
    let s = 2.0_f64.sqrt();
    [
        s * 1.0 / 16.0,
        s * 4.0 / 16.0,
        s * 6.0 / 16.0,
        s * 4.0 / 16.0,
        s * 1.0 / 16.0,
    ]
}

/// 1D Gaussian of length `len` with standard deviation `sigma`,
/// sampled at integer offsets `-half..=half` and normalised so the
/// taps sum to 1.
///
/// `fspecial` uses `-ws//2 + 1 .. ws//2 + 1` which for `len=11` is
/// `-5..=5` — symmetric about 0. Python's floor-division matches the
/// integer halve here.
///
/// `fspecial` also zeros entries below `eps * max`, then normalises.
/// For `sigma=1.5 / len=11` nothing is below `f32::EPSILON * max`
/// — verified analytically: smallest tap = `exp(-25/4.5) ≈ 3.87e-3`
/// >> `1.19e-7`. The trim step is skipped; that matches reference
/// output bit-for-bit.
pub fn gaussian_1d(len: usize, sigma: f64) -> Vec<f64> {
    let half = (len as i64) / 2;
    let mut g = Vec::with_capacity(len);
    let two_s2 = 2.0 * sigma * sigma;
    for k in -half..=half {
        let x = k as f64;
        g.push((-(x * x) / two_s2).exp());
    }
    let den: f64 = g.iter().sum();
    g.iter().map(|&v| v / den).collect()
}

/// Write the full `filters.rs` body to `out`. Called from each
/// crate's `build.rs` after creating an `OUT_DIR/filters.rs` file.
///
/// Emits:
/// - `pub const BINOM5_LEN: usize = 5;`
/// - `pub const BINOM5_RADIUS: i32 = 2;`
/// - `pub const BINOM5: [f32; 5] = [...];`
/// - `pub const SSIM_WIN_LEN: usize = 11;`
/// - `pub const SSIM_WIN_RADIUS: i32 = 5;`
/// - `pub const SSIM_WIN_1D: [f32; 11] = [...];`
/// - `pub const SCALE_WEIGHTS: [f32; 5] = [...];`
pub fn emit_filters_rs<W: Write>(out: &mut W) -> io::Result<()> {
    writeln!(out, "// Auto-generated by iwssim-filter-codegen — do not edit.")?;
    writeln!(out)?;

    // BINOM5 (separable 5-tap; same taps for both axes).
    let b = binom5_taps();
    writeln!(out, "pub const BINOM5_LEN: usize = 5;")?;
    writeln!(out, "pub const BINOM5_RADIUS: i32 = 2;")?;
    write!(out, "pub const BINOM5: [f32; 5] = [")?;
    for v in b.iter() {
        write!(out, "{:.20e}_f32, ", v)?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;

    // SSIM 11×11 Gaussian, σ=1.5 — applied separably as 1D 11-tap.
    let g = gaussian_1d(11, 1.5);
    writeln!(out, "pub const SSIM_WIN_LEN: usize = 11;")?;
    writeln!(out, "pub const SSIM_WIN_RADIUS: i32 = 5;")?;
    write!(out, "pub const SSIM_WIN_1D: [f32; 11] = [")?;
    for v in g.iter() {
        write!(out, "{:.20e}_f32, ", v)?;
    }
    writeln!(out, "];")?;
    writeln!(out)?;

    // Per-scale MS-SSIM combination weights (β in eq 47 of Wang & Li
    // 2011) — verbatim from `iwssim.m` / `IW_SSIM_PyTorch.py`.
    writeln!(
        out,
        "pub const SCALE_WEIGHTS: [f32; 5] = [\n    \
         4.48e-2_f32, 2.856e-1_f32, 3.001e-1_f32, 2.363e-1_f32, 1.333e-1_f32,\n];"
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn binom5_taps_sum_to_sqrt2() {
        let s: f64 = binom5_taps().iter().sum();
        let expected = 2.0_f64.sqrt();
        assert!((s - expected).abs() < 1e-15, "sum {s} != {expected}");
    }

    #[test]
    fn gaussian_1d_normalised() {
        let g = gaussian_1d(11, 1.5);
        let s: f64 = g.iter().sum();
        assert!((s - 1.0).abs() < 1e-15, "sum {s} != 1.0");
        assert_eq!(g.len(), 11);
    }

    #[test]
    fn emit_filters_rs_contains_all_constants() {
        let mut buf = Vec::new();
        emit_filters_rs(&mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("pub const BINOM5_LEN: usize = 5;"));
        assert!(s.contains("pub const BINOM5_RADIUS: i32 = 2;"));
        assert!(s.contains("pub const BINOM5: [f32; 5] = ["));
        assert!(s.contains("pub const SSIM_WIN_LEN: usize = 11;"));
        assert!(s.contains("pub const SSIM_WIN_RADIUS: i32 = 5;"));
        assert!(s.contains("pub const SSIM_WIN_1D: [f32; 11] = ["));
        assert!(s.contains("pub const SCALE_WEIGHTS: [f32; 5] = ["));
    }
}
