//! Filter coefficients generated by `build.rs`. Bit-identical to
//! `iwssim-gpu/src/filters.rs` by construction — both crates' build
//! scripts call the same shared helper at
//! `crates/iwssim-filter-codegen/`. Any drift would silently break
//! GPU/CPU parity, which the shared helper rules out.

// SSIM_WIN_RADIUS is currently read only in tests; suppress the
// dead-code warning rather than gating it behind cfg(test) (we may
// need it in production paths once boundary handling moves to SIMD).
#[allow(dead_code)]
mod consts {
    include!(concat!(env!("OUT_DIR"), "/filters.rs"));
}

pub(crate) use consts::*;
