//! Filter coefficients generated by `build.rs`. Bit-identical to
//! `iwssim-gpu/src/filters.rs` (same `build.rs`). Any drift here
//! silently breaks GPU/CPU parity.

include!(concat!(env!("OUT_DIR"), "/filters.rs"));
