//! Parity test for the host-scalar color transform.
//!
//! Cross-checks `cvvdp_gpu::kernels::color::srgb_byte_to_dkl_scalar`
//! against numbers produced by the pinned pycvvdp v0.5.4 reference at
//! f64 precision. Tolerances are loose enough to absorb the
//! f64 → f32 cast at the LUT + matrix boundaries, but tight enough
//! (1e-2 abs / 1e-4 rel on the achromatic channel) to catch any swap
//! of matrix rows or display-model constants.
//!
//! Goldens were generated by:
//!
//! ```text
//! scripts/cvvdp_goldens/.venv  →  python3 -c "<see commit message>"
//! ```
//!
//! against the `standard_4k` display model
//! (Y_peak=200, contrast=1000, E_ambient=250, k_refl=0.005, sRGB EOTF).
#![allow(clippy::excessive_precision)]

use cvvdp_gpu::kernels::color::srgb_byte_to_dkl_scalar;
use cvvdp_gpu::params::DisplayModel;

/// (r_byte, g_byte, b_byte, expected_A, expected_RG, expected_VY).
const GOLDENS: &[(u8, u8, u8, f32, f32, f32)] = &[
    (0, 0, 0, 0.628_396_27, 0.002_257_2, 0.006_174_458),
    (255, 255, 255, 210.623_77, 0.756_560_75, 2.069_534_3),
    (255, 0, 0, 47.222, 25.500_887, -42.915_363),
    (0, 255, 0, 146.248_79, -17.393_946, -125.119_31),
    (0, 0, 255, 18.409_771, -7.345_865_5, 170.116_56),
    (128, 64, 200, 28.422_167, 0.370_378_4, 82.578_43),
    (1, 2, 3, 0.747_129_5, -0.007_254_773, 0.072_087_97),
    (200, 100, 50, 46.664_63, 12.278_46, -35.304_32),
];

#[test]
fn matches_pycvvdp_standard_4k() {
    let d = DisplayModel::STANDARD_4K;

    for &(r, g, b, exp_a, exp_rg, exp_vy) in GOLDENS {
        let (a, rg, vy) = srgb_byte_to_dkl_scalar(r, g, b, d.y_peak, d.y_black, d.y_refl);

        // Achromatic channel spans 0..210 cd/m² — use absolute tol
        // appropriate to the magnitude. Chroma channels are smaller
        // in absolute terms so they need a tighter abs tol relative
        // to scale, but a percentage tol catches sign flips.
        let scale_a = exp_a.abs().max(1.0);
        let scale_rg = exp_rg.abs().max(1.0);
        let scale_vy = exp_vy.abs().max(1.0);

        let ea = (a - exp_a).abs() / scale_a;
        let erg = (rg - exp_rg).abs() / scale_rg;
        let evy = (vy - exp_vy).abs() / scale_vy;

        // 2e-3 (0.2 %) covers f32 cancellation in the chroma rows of
        // DKL (M[1] = [0.13, -0.09, -0.04] near-cancels for mid-tones);
        // exceeding it would need host-side f64 math or matrix
        // constants re-derived at single precision matching the
        // torch.tensor(dtype=float32) rounding used by pycvvdp.
        let tol = 2e-3_f32;
        assert!(
            ea < tol && erg < tol && evy < tol,
            "RGB({r},{g},{b}) → DKL: got ({a}, {rg}, {vy}), \
             expected ({exp_a}, {exp_rg}, {exp_vy}), \
             rel errs ({ea:.2e}, {erg:.2e}, {evy:.2e})"
        );
    }
}

#[test]
fn matrix_is_normalized_for_neutral_input() {
    // For an equal-energy linear input (r = g = b = 1.0 cd/m²), the
    // achromatic channel should equal the sum of the row, and the
    // chroma channels should be small in absolute terms (DKL's
    // chroma rows are mean-zero against equal-energy input by
    // construction). This catches matrix-row swaps that don't trip
    // the byte-level goldens above.
    use cvvdp_gpu::params::SRGB_LINEAR_TO_DKL as M;
    let a = M[0][0] + M[0][1] + M[0][2];
    let rg = M[1][0] + M[1][1] + M[1][2];
    let vy = M[2][0] + M[2][1] + M[2][2];

    // A row sums to RGB2Y(neutral) * Y2A_for_DKL = ~1.05 — but
    // depends on the combined matrix scale. Just check magnitudes
    // are sane and chroma sums smaller than achromatic.
    assert!(a > 0.5 && a < 2.0, "A row sum out of range: {a}");
    assert!(rg.abs() < a.abs(), "RG row sum {rg} should be < A {a}");
    assert!(vy.abs() < a.abs(), "VY row sum {vy} should be < A {a}");
}
