//! Parity test for the host-scalar color transform.
//!
//! Cross-checks `cvvdp_gpu::kernels::color::srgb_byte_to_dkl_scalar`
//! against numbers produced by the pinned pycvvdp v0.5.4 reference at
//! f64 precision. Tolerances are loose enough to absorb the
//! f64 → f32 cast at the LUT + matrix boundaries, but tight enough
//! (1e-2 abs / 1e-4 rel on the achromatic channel) to catch any swap
//! of matrix rows or display-model constants.
//!
//! Goldens were generated by:
//!
//! ```text
//! scripts/cvvdp_goldens/.venv  →  python3 -c "<see commit message>"
//! ```
//!
//! against the `standard_4k` display model
//! (Y_peak=200, contrast=1000, E_ambient=250, k_refl=0.005, sRGB EOTF).
#![allow(clippy::excessive_precision)]

use cvvdp_gpu::kernels::color::{SRGB8_TO_LINEAR_LUT, srgb_byte_to_dkl_scalar};
use cvvdp_gpu::params::DisplayModel;

// Tick 549: compile-time pin of the sRGB→linear LUT size. One entry
// per u8 byte = 256 entries; this is the byte-domain LUT contract
// the `srgb_byte_to_dkl_scalar` and `srgb_to_dkl_kernel` paths both
// index. A refactor that switched to a partial / sub-sampled LUT
// would change indexing semantics silently. Same pattern as ticks
// 522-524 + 548 + the other promotions in this tick.
const _: () = assert!(
    SRGB8_TO_LINEAR_LUT.len() == 256,
    "SRGB8_TO_LINEAR_LUT must have one entry per u8 value (256)",
);

// Tick 561: compile-time pin of the LUT endpoints. The IEC
// 61966-2-1 sRGB EOTF maps byte 0 → linear 0.0 exactly and byte
// 255 → linear 1.0 exactly. A refactor that off-by-ones the byte
// index, or accidentally drops the byte=255 boundary case, would
// silently shift every pixel's linear-space contribution. Pinning
// the two boundary entries at compile time catches that class of
// error before any pipeline runs.
const _: () = assert!(
    SRGB8_TO_LINEAR_LUT[0].to_bits() == 0.0_f32.to_bits(),
    "SRGB8_TO_LINEAR_LUT[0] must be exactly 0.0 (sRGB byte 0 → linear 0)",
);
const _: () = assert!(
    SRGB8_TO_LINEAR_LUT[255].to_bits() == 1.0_f32.to_bits(),
    "SRGB8_TO_LINEAR_LUT[255] must be exactly 1.0 (sRGB byte 255 → linear 1.0 full-scale)",
);

/// (r_byte, g_byte, b_byte, expected_A, expected_RG, expected_VY).
const GOLDENS: &[(u8, u8, u8, f32, f32, f32)] = &[
    (0, 0, 0, 0.628_396_27, 0.002_257_2, 0.006_174_458),
    (255, 255, 255, 210.623_77, 0.756_560_75, 2.069_534_3),
    (255, 0, 0, 47.222, 25.500_887, -42.915_363),
    (0, 255, 0, 146.248_79, -17.393_946, -125.119_31),
    (0, 0, 255, 18.409_771, -7.345_865_5, 170.116_56),
    (128, 64, 200, 28.422_167, 0.370_378_4, 82.578_43),
    (1, 2, 3, 0.747_129_5, -0.007_254_773, 0.072_087_97),
    (200, 100, 50, 46.664_63, 12.278_46, -35.304_32),
];

#[test]
fn matches_pycvvdp_standard_4k() {
    let d = DisplayModel::STANDARD_4K;

    for &(r, g, b, exp_a, exp_rg, exp_vy) in GOLDENS {
        let (a, rg, vy) = srgb_byte_to_dkl_scalar(r, g, b, d.y_peak, d.y_black, d.y_refl);

        // Achromatic channel spans 0..210 cd/m² — use absolute tol
        // appropriate to the magnitude. Chroma channels are smaller
        // in absolute terms so they need a tighter abs tol relative
        // to scale, but a percentage tol catches sign flips.
        let scale_a = exp_a.abs().max(1.0);
        let scale_rg = exp_rg.abs().max(1.0);
        let scale_vy = exp_vy.abs().max(1.0);

        let ea = (a - exp_a).abs() / scale_a;
        let erg = (rg - exp_rg).abs() / scale_rg;
        let evy = (vy - exp_vy).abs() / scale_vy;

        // 2e-3 (0.2 %) covers f32 cancellation in the chroma rows of
        // DKL (M[1] = [0.13, -0.09, -0.04] near-cancels for mid-tones);
        // exceeding it would need host-side f64 math or matrix
        // constants re-derived at single precision matching the
        // torch.tensor(dtype=float32) rounding used by pycvvdp.
        let tol = 2e-3_f32;
        assert!(
            ea < tol && erg < tol && evy < tol,
            "RGB({r},{g},{b}) → DKL: got ({a}, {rg}, {vy}), \
             expected ({exp_a}, {exp_rg}, {exp_vy}), \
             rel errs ({ea:.2e}, {erg:.2e}, {evy:.2e})"
        );
    }
}

// `SRGB8_TO_LINEAR_LUT` is the 256-entry public sRGB EOTF table
// that every color-stage call indexes. A historical regression in
// the LUT itself (~6e-4 drift at bright bytes, mentioned in
// `pipeline_color.rs:2009`) shipped because the 8-point goldens
// in `matches_pycvvdp_standard_4k` happened to sample only a
// handful of bytes — a refactor that breaks the LUT at, say, byte
// 200 specifically can still pass those goldens. Pin the LUT
// directly against the IEC 61966-2-1 sRGB EOTF formula at all
// 256 bytes so any per-byte regression surfaces here before
// propagating into pipeline drift.

#[test]
fn srgb_lut_length_and_endpoints() {
    // Length 256 (one entry per u8). LUT[0] = 0.0 exactly
    // (sRGB at 0 maps to linear 0). LUT[255] = 1.0 exactly
    // (sRGB at 255 maps to linear 1.0 — full-scale). Pin these
    // endpoints so a refactor that off-by-ones the index or
    // accidentally drops the 255 boundary trips here.
    assert_eq!(SRGB8_TO_LINEAR_LUT.len(), 256);
    assert_eq!(
        SRGB8_TO_LINEAR_LUT[0].to_bits(),
        0.0_f32.to_bits(),
        "LUT[0] = {}, expected exactly 0.0",
        SRGB8_TO_LINEAR_LUT[0]
    );
    assert_eq!(
        SRGB8_TO_LINEAR_LUT[255].to_bits(),
        1.0_f32.to_bits(),
        "LUT[255] = {}, expected exactly 1.0",
        SRGB8_TO_LINEAR_LUT[255]
    );
}

#[test]
fn srgb_lut_is_strictly_monotonic() {
    // sRGB EOTF is a strictly monotonic increasing function on
    // [0, 1], so the LUT MUST be strictly increasing. A bit-flip
    // anywhere in the table (or worse: a swapped pair of entries
    // due to a copy-paste error) would break this. Catches the
    // exact shape of regression that the pre-tick-X "~6e-4 drift
    // at bright bytes" represented.
    for i in 1..256 {
        assert!(
            SRGB8_TO_LINEAR_LUT[i] > SRGB8_TO_LINEAR_LUT[i - 1],
            "LUT not strictly monotonic at index {i}: LUT[{}]={}, LUT[{i}]={}",
            i - 1,
            SRGB8_TO_LINEAR_LUT[i - 1],
            SRGB8_TO_LINEAR_LUT[i],
        );
    }
}

#[test]
fn srgb_lut_matches_iec_61966_2_1_formula() {
    // Direct evaluation of the sRGB inverse companding formula at
    // every byte:
    //   c = byte / 255
    //   lin = if c ≤ 0.04045 { c / 12.92 } else { ((c + 0.055) / 1.055)^2.4 }
    // Reference: IEC 61966-2-1:1999 Annex A. Compute at f64 then
    // compare to the f32 LUT; tolerate up to 1e-6 absolute (well
    // under the 6e-4 historic drift) so f64→f32 cast noise doesn't
    // trip the gate. Sweeping all 256 bytes catches per-byte
    // regressions that the 8 goldens above never look at.
    for byte in 0..=255_u8 {
        let c = f64::from(byte) / 255.0;
        let expected = if c <= 0.04045 {
            c / 12.92
        } else {
            ((c + 0.055) / 1.055).powf(2.4)
        } as f32;
        let got = SRGB8_TO_LINEAR_LUT[byte as usize];
        let abs_err = (got - expected).abs();
        assert!(
            abs_err < 1e-6,
            "LUT[{byte}] = {got}, expected ~{expected} (|err| = {abs_err:.4e})",
        );
    }
}

#[test]
fn srgb_lut_branch_seam_continuity() {
    // The sRGB EOTF has a piecewise definition that joins at
    // c = 0.04045 (≈ byte 10.31). f32 LUT entries at bytes 10 and
    // 11 straddle the seam; they should still be smoothly
    // increasing. Pin so a refactor that mis-aligns the branch
    // threshold (e.g. uses 0.04 instead of 0.04045) produces a
    // local discontinuity that we catch here, even if the global
    // monotonicity test still passes.
    let d_low = SRGB8_TO_LINEAR_LUT[11] - SRGB8_TO_LINEAR_LUT[10];
    let d_high = SRGB8_TO_LINEAR_LUT[12] - SRGB8_TO_LINEAR_LUT[11];
    // Per-step difference at the seam should be small and similar.
    // The pre-seam slope is 1/(12.92 * 255) ≈ 3.04e-4; post-seam at
    // c ≈ 0.04 is slightly steeper but not by orders of magnitude.
    let ratio = d_high / d_low.max(1e-9);
    assert!(
        ratio > 0.5 && ratio < 2.0,
        "Seam slope discontinuity at byte 11: d[10..11]={d_low}, d[11..12]={d_high}, ratio={ratio}",
    );
}

#[test]
fn matrix_is_normalized_for_neutral_input() {
    // For an equal-energy linear input (r = g = b = 1.0 cd/m²), the
    // achromatic channel should equal the sum of the row, and the
    // chroma channels should be small in absolute terms (DKL's
    // chroma rows are mean-zero against equal-energy input by
    // construction). This catches matrix-row swaps that don't trip
    // the byte-level goldens above.
    use cvvdp_gpu::params::SRGB_LINEAR_TO_DKL as M;
    let a = M[0][0] + M[0][1] + M[0][2];
    let rg = M[1][0] + M[1][1] + M[1][2];
    let vy = M[2][0] + M[2][1] + M[2][2];

    // A row sums to RGB2Y(neutral) * Y2A_for_DKL = ~1.05 — but
    // depends on the combined matrix scale. Just check magnitudes
    // are sane and chroma sums smaller than achromatic.
    assert!(a > 0.5 && a < 2.0, "A row sum out of range: {a}");
    assert!(rg.abs() < a.abs(), "RG row sum {rg} should be < A {a}");
    assert!(vy.abs() < a.abs(), "VY row sum {vy} should be < A {a}");
}

// Pin the exact f32 bit patterns of every entry in
// `SRGB_LINEAR_TO_DKL`. The matrix is documented (in
// `params.rs`) as the composition
// `LMS2006_to_DKLd65 @ XYZ_to_LMS2006 @ sRGB_to_XYZ` computed
// at f64 precision and rounded to f32. The existing
// `matrix_is_normalized_for_neutral_input` test only checks row-
// sum signs/magnitudes — a refactor that swaps two entries
// within a row (or substitutes different but plausible-looking
// values from a related matrix, e.g. LMS2000 instead of LMS2006)
// could preserve the row-sum heuristic but still drift every
// DKL output. Pin each of the 9 entries explicitly with
// `.to_bits()` for unambiguous regression detection.

#[test]
fn srgb_linear_to_dkl_matrix_matches_pycvvdp_v0_5_4() {
    use cvvdp_gpu::params::SRGB_LINEAR_TO_DKL as M;

    // Row 0 — achromatic (A) channel. All positive (achromatic
    // is a weighted sum of R, G, B).
    let row0_expected: [f32; 3] = [0.233_201_21, 0.728_830_8, 0.088_995_87];
    for (i, (got, exp)) in M[0].iter().zip(row0_expected.iter()).enumerate() {
        assert_eq!(
            got.to_bits(),
            exp.to_bits(),
            "SRGB_LINEAR_TO_DKL[0][{i}] (A) = {got}, expected {exp}",
        );
    }

    // Row 1 — red-green (RG) chroma. Mixed signs: opposes R
    // against (G + B).
    let row1_expected: [f32; 3] = [0.127_620_77, -0.087_068_09, -0.036_777_39];
    for (i, (got, exp)) in M[1].iter().zip(row1_expected.iter()).enumerate() {
        assert_eq!(
            got.to_bits(),
            exp.to_bits(),
            "SRGB_LINEAR_TO_DKL[1][{i}] (Rg) = {got}, expected {exp}",
        );
    }

    // Row 2 — violet-yellow (VY) chroma. Mixed signs: opposes B
    // against (R + G).
    let row2_expected: [f32; 3] = [-0.214_822_5, -0.626_253_7, 0.851_403_3];
    for (i, (got, exp)) in M[2].iter().zip(row2_expected.iter()).enumerate() {
        assert_eq!(
            got.to_bits(),
            exp.to_bits(),
            "SRGB_LINEAR_TO_DKL[2][{i}] (Vy) = {got}, expected {exp}",
        );
    }
}

#[test]
fn srgb_linear_to_dkl_row_sign_signature() {
    // Per the DKL opponent-color construction:
    //   - Row 0 (A) must have ALL three entries positive.
    //   - Row 1 (Rg) must have a positive [0] and negative [1],
    //     [2] (red opposed to green+blue).
    //   - Row 2 (Vy) must have a positive [2] only ([0], [1] are
    //     negative — blue opposed to red+green).
    // These signs are part of the opponent-color contract.
    // A refactor that drops a minus sign somewhere preserves
    // magnitude-based row-sum heuristics but breaks chromaticity.
    use cvvdp_gpu::params::SRGB_LINEAR_TO_DKL as M;

    assert!(
        M[0][0] > 0.0 && M[0][1] > 0.0 && M[0][2] > 0.0,
        "Row 0 (A) must be all-positive: {:?}",
        M[0],
    );
    assert!(
        M[1][0] > 0.0 && M[1][1] < 0.0 && M[1][2] < 0.0,
        "Row 1 (Rg) must be (+, -, -): {:?}",
        M[1],
    );
    assert!(
        M[2][0] < 0.0 && M[2][1] < 0.0 && M[2][2] > 0.0,
        "Row 2 (Vy) must be (-, -, +): {:?}",
        M[2],
    );
}
