//! Parity test for `gausspyr_reduce_scalar` and `gausspyr_expand_scalar`.
//!
//! Cross-checks against pycvvdp v0.5.4's `lpyr_dec.gausspyr_reduce` /
//! `gausspyr_expand` on a deterministic 8×8 ramp-with-peak input. The
//! goldens are baked inline — they're small (16 + 64 f32) and locking
//! them in source makes the test reproducible without network access.
//!
//! Generated by:
//!
//! ```python
//! import torch, numpy as np, pycvvdp.lpyr_dec as L
//! inp = np.array([[i + 4*j + (1.0 if i == 3 and j == 5 else 0.0)
//!                  for i in range(8)] for j in range(8)], dtype=np.float32)
//! x = torch.from_numpy(inp).view(1, 1, 1, 8, 8)
//! dec = L.lpyr_dec(W=8, H=8, ppd=60.0, device='cpu')
//! reduce = dec.gausspyr_reduce(x, kernel_a=0.4)
//! expand = dec.gausspyr_expand(reduce, sz=[8, 8], kernel_a=0.4)
//! ```
#![allow(clippy::excessive_precision)]

use cvvdp_gpu::kernels::pyramid::{
    band_frequencies, gausspyr_expand_scalar, gausspyr_reduce_scalar, laplacian_pyramid_dec_scalar,
};

#[rustfmt::skip]
const INPUT_8X8: [f32; 64] = [
    0.0,  1.0,  2.0,  3.0,  4.0,  5.0,  6.0,  7.0,
    4.0,  5.0,  6.0,  7.0,  8.0,  9.0, 10.0, 11.0,
    8.0,  9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0,
   12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0,
   16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0,
   20.0, 21.0, 22.0, 24.0, 24.0, 25.0, 26.0, 27.0,
   24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0,
   28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0,
];

// Note the (row=5, col=3) value is 24.0 not 23.0 — that's the
// "+1.0 if i==3 and j==5" peak the Python generator inserts. Keeps the
// input from being purely separable so the parity test exercises both
// the vertical and horizontal pass coefficients.

#[rustfmt::skip]
const REDUCE_4X4: [f32; 16] = [
    2.0,            3.5999997,      5.6000004,      7.5500002,
    8.3999996,     10.0,           12.0,           13.950001,
   16.4,           18.0625,        20.0625,        21.950001,
   24.200003,      25.862499,      27.862501,      29.750004,
];

#[rustfmt::skip]
const EXPAND_8X8: [f32; 64] = [
    2.8,            3.4399998,      4.2799997,      5.2400002,
    6.2350006,      7.2150006,      7.9950008,      8.1900005,
    5.3599997,      6.0,            6.8400002,      7.8000002,
    8.7950001,      9.7749996,     10.555,         10.75,
    8.7206249,      9.3631248,     10.205625,     11.16625,
   12.160626,      13.138126,      13.915627,     14.110001,
   12.563125,     13.215625,      14.068125,     15.03125,
   16.023125,     16.990625,      17.758125,     17.950001,
   16.545626,     17.208126,      18.070625,     19.036251,
   20.025627,     20.983128,      21.740629,     21.930002,
   20.466251,     21.13125,       21.99625,      22.962502,
   23.951254,     24.906252,      25.661253,     25.850002,
   23.586252,     24.251251,      25.116251,     26.0825,
   27.071251,     28.026253,      28.781254,     28.970003,
   24.366253,     25.03125,       25.896252,     26.862499,
   27.851252,     28.806252,      29.561255,     29.750004,
];

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

#[test]
fn reduce_matches_pycvvdp() {
    let mut dst = Vec::new();
    let (dw, dh) = gausspyr_reduce_scalar(&INPUT_8X8, 8, 8, &mut dst);
    assert_eq!((dw, dh), (4, 4));

    let max_err = max_abs_diff(&dst, &REDUCE_4X4);
    assert!(
        max_err < 1e-4,
        "reduce max-abs error vs pycvvdp = {max_err}, expected < 1e-4\n\
         rust = {dst:?}\n\
         pycvvdp = {:?}",
        &REDUCE_4X4[..]
    );
}

#[test]
fn expand_matches_pycvvdp() {
    let mut dst = Vec::new();
    gausspyr_expand_scalar(&REDUCE_4X4, 4, 4, 8, 8, &mut dst);

    let max_err = max_abs_diff(&dst, &EXPAND_8X8);
    assert!(
        max_err < 1e-4,
        "expand max-abs error vs pycvvdp = {max_err}, expected < 1e-4\n\
         rust = {dst:?}\n\
         pycvvdp = {:?}",
        &EXPAND_8X8[..]
    );
}

#[rustfmt::skip]
const LAPLACIAN_BAND_0: [f32; 64] = [
    -2.8,         -2.4399998,   -2.2799997,   -2.2400002,   -2.2350006,   -2.2150006,   -1.9950008,   -1.1900005,
    -1.3599997,   -1.0,         -0.84000015,  -0.80000019,  -0.79500008,  -0.77499962,  -0.55500031,   0.25,
    -0.72062492,  -0.36312485,  -0.20562458,  -0.16625023,  -0.16062641,  -0.13812637,   0.084373474,  0.88999939,
    -0.56312466,  -0.21562481,  -0.06812477,  -0.03125,     -0.023124695,  0.0093746185, 0.24187469,   1.0499992,
    -0.54562569,  -0.20812607,  -0.070625305, -0.036251068, -0.025627136,  0.016872406,  0.2593708,    1.0699978,
    -0.46625137,  -0.13125038,   0.0037498474, 1.0374985,    0.048746109,  0.093748093,  0.33874702,   1.1499977,
     0.41374779,   0.74874878,   0.88374901,   0.91749954,   0.92874908,   0.97374725,   1.2187462,    2.0299969,
     3.6337471,    3.96875,      4.1037483,    4.1375008,    4.1487484,    4.1937485,    4.4387455,    5.2499962,
];

#[rustfmt::skip]
const LAPLACIAN_BAND_1: [f32; 16] = [
    -4.7252316,   -4.2640944,   -3.402956,    -1.7376719,
    -2.8834076,   -2.4242191,   -1.5650311,    0.099765778,
     0.55841541,   1.0781555,    1.9353924,    3.5372028,
     7.2188759,   7.7381229,    8.5948753,    10.196566,
];

#[rustfmt::skip]
const LAPLACIAN_BAND_2: [f32; 4] = [
     5.3010941,   8.1470318,
    16.695314,   19.553438,
];

#[test]
fn laplacian_3_levels_matches_pycvvdp() {
    let bands = laplacian_pyramid_dec_scalar(&INPUT_8X8, 8, 8, 3);
    assert_eq!(bands.len(), 3);
    assert_eq!((bands[0].w, bands[0].h), (8, 8));
    assert_eq!((bands[1].w, bands[1].h), (4, 4));
    assert_eq!((bands[2].w, bands[2].h), (2, 2));

    let e0 = max_abs_diff(&bands[0].data, &LAPLACIAN_BAND_0);
    let e1 = max_abs_diff(&bands[1].data, &LAPLACIAN_BAND_1);
    let e2 = max_abs_diff(&bands[2].data, &LAPLACIAN_BAND_2);
    assert!(e0 < 1e-4, "band 0 max-abs vs pycvvdp = {e0}");
    assert!(e1 < 1e-4, "band 1 max-abs vs pycvvdp = {e1}");
    assert!(e2 < 1e-4, "band 2 max-abs vs pycvvdp = {e2}");
}

#[test]
fn one_band_laplacian_matches_pycvvdp() {
    // A Laplacian pyramid level k is `fine - expand(reduce(fine))`.
    // Compute that one-level band in Rust and check that, when we
    // re-add it to expand(reduce(input)), we recover the input bit-
    // exact (or within tight f32 tol).
    let mut reduced = Vec::new();
    gausspyr_reduce_scalar(&INPUT_8X8, 8, 8, &mut reduced);
    let mut expanded = Vec::new();
    gausspyr_expand_scalar(&reduced, 4, 4, 8, 8, &mut expanded);

    let band: Vec<f32> = INPUT_8X8
        .iter()
        .zip(&expanded)
        .map(|(a, b)| a - b)
        .collect();
    let recon: Vec<f32> = band.iter().zip(&expanded).map(|(b, e)| b + e).collect();

    let max_err = max_abs_diff(&recon, &INPUT_8X8);
    assert!(
        max_err < 1e-5,
        "band + expand(reduce) reconstruction error = {max_err}"
    );
}

#[test]
fn band_frequencies_match_pycvvdp() {
    // Goldens generated via:
    //   dec = pycvvdp.lpyr_dec.lpyr_dec(W=256, H=256, ppd=PPD, device='cpu')
    //   print(dec.get_freqs())
    // All for 256×256 inputs at the listed PPD. Each returned vec is
    // 8 entries long (max_levels=7, n_levels=7, +1 for the base).
    let cases: &[(f32, [f32; 8])] = &[
        (
            37.701_225,
            [
                18.850_612, 6.084_978, 3.042_489, 1.521_244, 0.760_622, 0.380_311, 0.190_156,
                0.095_078,
            ],
        ),
        (
            60.0,
            [
                30.0,
                9.684,
                4.842,
                2.421,
                1.2105,
                0.605_25,
                0.302_625,
                0.151_312_5,
            ],
        ),
        (
            32.0,
            [16.0, 5.1648, 2.5824, 1.2912, 0.6456, 0.3228, 0.1614, 0.0807],
        ),
        (
            90.0,
            [
                45.0,
                14.526,
                7.263,
                3.6315,
                1.815_75,
                0.907_875,
                0.453_937_5,
                0.226_968_75,
            ],
        ),
    ];
    for &(ppd, ref expected) in cases {
        let got = band_frequencies(ppd, 256, 256);
        assert_eq!(
            got.len(),
            expected.len(),
            "len mismatch for ppd={ppd}: got {} entries, expected {}",
            got.len(),
            expected.len()
        );
        let max_err = got
            .iter()
            .zip(expected)
            .map(|(a, b)| (a - b).abs())
            .fold(0.0_f32, f32::max);
        assert!(
            max_err < 1e-4,
            "ppd={ppd}: max-abs error vs pycvvdp = {max_err}\n  got = {got:?}\n  exp = {expected:?}"
        );
    }
}

#[test]
fn band_frequencies_match_v1_manifest() {
    // The v1 R2 goldens were captured for the standard_4k display
    // (cvvdp's internally-computed PPD is ~75.402). The manifest's
    // rho_band field is documented as:
    //   [37.701, 12.170, 6.085, 3.042, 1.521, 0.761, 0.380, 0.100]
    //
    // Our band_frequencies(ppd=75.402, 256, 256) reproduces the
    // first 7 entries; the 8th (0.100) is a slight cvvdp quirk where
    // the highest-frequency band gets a special clamped value rather
    // than the geometric continuation. The clamp lives outside
    // band_frequencies and would be applied by the masking/pooling
    // call site — flag it explicitly so the test doesn't pretend
    // they match end-to-end.
    let got = band_frequencies(75.402_25, 256, 256);
    let manifest_first_7 = [
        37.701_226_f32,
        12.169_955,
        6.084_978,
        3.042_489,
        1.521_244,
        0.760_622,
        0.380_311,
    ];
    assert_eq!(got.len(), 8);
    let max_err = got[..7]
        .iter()
        .zip(&manifest_first_7)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0_f32, f32::max);
    assert!(
        max_err < 1e-3,
        "first 7 manifest entries: max-abs = {max_err}"
    );
}
