//! Parity test for `gausspyr_reduce_scalar` and `gausspyr_expand_scalar`.
//!
//! Cross-checks against pycvvdp v0.5.4's `lpyr_dec.gausspyr_reduce` /
//! `gausspyr_expand` on a deterministic 8×8 ramp-with-peak input. The
//! goldens are baked inline — they're small (16 + 64 f32) and locking
//! them in source makes the test reproducible without network access.
//!
//! Generated by:
//!
//! ```python
//! import torch, numpy as np, pycvvdp.lpyr_dec as L
//! inp = np.array([[i + 4*j + (1.0 if i == 3 and j == 5 else 0.0)
//!                  for i in range(8)] for j in range(8)], dtype=np.float32)
//! x = torch.from_numpy(inp).view(1, 1, 1, 8, 8)
//! dec = L.lpyr_dec(W=8, H=8, ppd=60.0, device='cpu')
//! reduce = dec.gausspyr_reduce(x, kernel_a=0.4)
//! expand = dec.gausspyr_expand(reduce, sz=[8, 8], kernel_a=0.4)
//! ```

use cvvdp_gpu::kernels::pyramid::{gausspyr_expand_scalar, gausspyr_reduce_scalar};

#[rustfmt::skip]
const INPUT_8X8: [f32; 64] = [
    0.0,  1.0,  2.0,  3.0,  4.0,  5.0,  6.0,  7.0,
    4.0,  5.0,  6.0,  7.0,  8.0,  9.0, 10.0, 11.0,
    8.0,  9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0,
   12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0,
   16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0,
   20.0, 21.0, 22.0, 24.0, 24.0, 25.0, 26.0, 27.0,
   24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0,
   28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0,
];

// Note the (row=5, col=3) value is 24.0 not 23.0 — that's the
// "+1.0 if i==3 and j==5" peak the Python generator inserts. Keeps the
// input from being purely separable so the parity test exercises both
// the vertical and horizontal pass coefficients.

#[rustfmt::skip]
const REDUCE_4X4: [f32; 16] = [
    2.0,            3.5999997,      5.6000004,      7.5500002,
    8.3999996,     10.0,           12.0,           13.950001,
   16.4,           18.0625,        20.0625,        21.950001,
   24.200003,      25.862499,      27.862501,      29.750004,
];

#[rustfmt::skip]
const EXPAND_8X8: [f32; 64] = [
    2.8,            3.4399998,      4.2799997,      5.2400002,
    6.2350006,      7.2150006,      7.9950008,      8.1900005,
    5.3599997,      6.0,            6.8400002,      7.8000002,
    8.7950001,      9.7749996,     10.555,         10.75,
    8.7206249,      9.3631248,     10.205625,     11.16625,
   12.160626,      13.138126,      13.915627,     14.110001,
   12.563125,     13.215625,      14.068125,     15.03125,
   16.023125,     16.990625,      17.758125,     17.950001,
   16.545626,     17.208126,      18.070625,     19.036251,
   20.025627,     20.983128,      21.740629,     21.930002,
   20.466251,     21.13125,       21.99625,      22.962502,
   23.951254,     24.906252,      25.661253,     25.850002,
   23.586252,     24.251251,      25.116251,     26.0825,
   27.071251,     28.026253,      28.781254,     28.970003,
   24.366253,     25.03125,       25.896252,     26.862499,
   27.851252,     28.806252,      29.561255,     29.750004,
];

fn max_abs_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

#[test]
fn reduce_matches_pycvvdp() {
    let mut dst = Vec::new();
    let (dw, dh) = gausspyr_reduce_scalar(&INPUT_8X8, 8, 8, &mut dst);
    assert_eq!((dw, dh), (4, 4));

    let max_err = max_abs_diff(&dst, &REDUCE_4X4);
    assert!(
        max_err < 1e-4,
        "reduce max-abs error vs pycvvdp = {max_err}, expected < 1e-4\n\
         rust = {dst:?}\n\
         pycvvdp = {:?}",
        &REDUCE_4X4[..]
    );
}

#[test]
fn expand_matches_pycvvdp() {
    let mut dst = Vec::new();
    gausspyr_expand_scalar(&REDUCE_4X4, 4, 4, 8, 8, &mut dst);

    let max_err = max_abs_diff(&dst, &EXPAND_8X8);
    assert!(
        max_err < 1e-4,
        "expand max-abs error vs pycvvdp = {max_err}, expected < 1e-4\n\
         rust = {dst:?}\n\
         pycvvdp = {:?}",
        &EXPAND_8X8[..]
    );
}

#[test]
fn one_band_laplacian_matches_pycvvdp() {
    // A Laplacian pyramid level k is `fine - expand(reduce(fine))`.
    // Compute that one-level band in Rust and check that, when we
    // re-add it to expand(reduce(input)), we recover the input bit-
    // exact (or within tight f32 tol).
    let mut reduced = Vec::new();
    gausspyr_reduce_scalar(&INPUT_8X8, 8, 8, &mut reduced);
    let mut expanded = Vec::new();
    gausspyr_expand_scalar(&reduced, 4, 4, 8, 8, &mut expanded);

    let band: Vec<f32> = INPUT_8X8
        .iter()
        .zip(&expanded)
        .map(|(a, b)| a - b)
        .collect();
    let recon: Vec<f32> = band.iter().zip(&expanded).map(|(b, e)| b + e).collect();

    let max_err = max_abs_diff(&recon, &INPUT_8X8);
    assert!(
        max_err < 1e-5,
        "band + expand(reduce) reconstruction error = {max_err}"
    );
}
