//! sRGB byte → linear-f32 conversion.
//!
//! Pointwise translation of `ssimulacra2-cuda-kernel/src/srgb.rs`.
//! The CUDA reference uses a 256-entry LUT; we compute the transfer
//! function inline so the kernel is self-contained across backends. At
//! byte resolution (256 inputs) the formula is bit-exact with the LUT
//! values: each LUT entry was generated by exactly this expression at
//! `i / 255.0`.
//!
//! The transfer function matches the published `ssimulacra2` /
//! `yuvxyb::srgb_gamma_to_lin` (gamma 2.4 with linear toe), and is the
//! same one used by the original SSIMULACRA reference for "viewing in
//! darker conditions".

use cubecl::prelude::*;

/// Adjusted for continuity of first derivative — verbatim from the CUDA
/// kernel and from `yuvxyb`.
const SRGB_ALPHA: f32 = 1.055_010_7;
const SRGB_BETA: f32 = 0.003_041_282_5;

/// Per-pixel sRGB u8 (packed RGB) → planar linear f32 RGB.
///
/// `src` holds `n_pixels × 3` bytes interleaved; `dst_r/g/b` each get
/// `n_pixels` f32 in [0, 1].
#[cube(launch_unchecked)]
pub fn srgb_u8_to_linear_planar_kernel(
    src: &Array<u8>,
    dst_r: &mut Array<f32>,
    dst_g: &mut Array<f32>,
    dst_b: &mut Array<f32>,
) {
    let idx = ABSOLUTE_POS;
    let n = dst_r.len();
    if idx >= n {
        terminate!();
    }
    let i3 = idx * 3;
    dst_r[idx] = srgb_byte_to_linear(src[i3]);
    dst_g[idx] = srgb_byte_to_linear(src[i3 + 1]);
    dst_b[idx] = srgb_byte_to_linear(src[i3 + 2]);
}

/// sRGB transfer function with linear toe; gamma 2.4 (SSIMULACRA's
/// "darker viewing" gamma).
#[cube]
fn srgb_byte_to_linear(v: u8) -> f32 {
    let f = (v as f32) * (1.0 / 255.0);
    if f < 12.92 * SRGB_BETA {
        f / 12.92
    } else {
        f32::powf((f + (SRGB_ALPHA - 1.0)) / SRGB_ALPHA, 2.4)
    }
}
