//! sRGB byte → linear-f32 conversion.
//!
//! Pointwise translation of `ssimulacra2-cuda-kernel/src/srgb.rs`.
//! The CUDA reference uses a 256-entry LUT; we compute the transfer
//! function inline so the kernel is self-contained across backends. At
//! byte resolution (256 inputs) the formula is bit-exact with the LUT
//! values: each LUT entry was generated by exactly this expression at
//! `i / 255.0`.
//!
//! The transfer function matches the published `ssimulacra2` /
//! `yuvxyb::srgb_gamma_to_lin` (gamma 2.4 with linear toe), and is the
//! same one used by the original SSIMULACRA reference for "viewing in
//! darker conditions".

use cubecl::prelude::*;

/// Adjusted for continuity of first derivative — verbatim from the CUDA
/// kernel and from `yuvxyb`.
const SRGB_ALPHA: f32 = 1.055_010_7;
const SRGB_BETA: f32 = 0.003_041_282_5;

/// Per-pixel sRGB byte → planar linear f32 RGB.
///
/// T4.L (2026-05-16): `src` is one packed-RGBA u32 per pixel
/// (R | G<<8 | B<<16; alpha unused). Cuts host→device upload 3× vs
/// the prior one-byte-per-u32 layout (12 bytes/pixel → 4 bytes/pixel),
/// which nsys identified as the dominant warm-loop cost on cvvdp-gpu
/// before the same fix landed there. See `docs/CUBECL_GOTCHAS.md` G6.6.
/// 3 bit-shifts + 3 ANDs per pixel are free relative to the saved
/// upload bandwidth.
///
/// Output: `dst_r/g/b` each `n_pixels` f32 in [0, 1].
#[cube(launch_unchecked)]
pub fn srgb_u8_to_linear_planar_kernel(
    src: &Array<u32>,
    dst_r: &mut Array<f32>,
    dst_g: &mut Array<f32>,
    dst_b: &mut Array<f32>,
) {
    let idx = ABSOLUTE_POS;
    let n = dst_r.len();
    if idx >= n {
        terminate!();
    }
    let packed = src[idx];
    let r = packed & 0xffu32;
    let g = (packed >> 8u32) & 0xffu32;
    let b = (packed >> 16u32) & 0xffu32;
    dst_r[idx] = srgb_byte_to_linear(r);
    dst_g[idx] = srgb_byte_to_linear(g);
    dst_b[idx] = srgb_byte_to_linear(b);
}

/// sRGB transfer function with linear toe; gamma 2.4 (SSIMULACRA's
/// "darker viewing" gamma).
#[cube]
fn srgb_byte_to_linear(v: u32) -> f32 {
    let f = (v as f32) * (1.0 / 255.0);
    if f < 12.92 * SRGB_BETA {
        f / 12.92
    } else {
        f32::powf((f + (SRGB_ALPHA - 1.0)) / SRGB_ALPHA, 2.4)
    }
}
