//! Filter coefficients generated by `build.rs`. Re-exported as
//! crate-level `pub const` so kernels can read them at compile time.
//!
//! Phase 8g.1 — these constants (`BINOM5`, `SSIM_WIN_1D`,
//! `SCALE_WEIGHTS`) are intentionally **duplicated** between
//! `iwssim` and `iwssim-gpu`. They cannot move to a single source-of-
//! truth because the cube-macros that consume them (`lap_pyramid`,
//! `gauss11` `#[cube(launch_unchecked)]` kernels) require the
//! constants to resolve through the **local** crate path `crate::filters`
//! at macro-expansion time. Pulling them via `iwssim::filters::*`
//! (or `pub use iwssim::filters::BINOM5;`) is not name-resolvable inside
//! a `#[cube]` body — the cube codegen captures `crate`-relative paths
//! and re-emits them on the device side.
//!
//! The two crates' `build.rs` files are bit-identical (`crates/iwssim/
//! build.rs` and `crates/iwssim-gpu/build.rs`) so the emitted
//! constants are guaranteed equal — any drift between the two
//! `build.rs` files would silently break GPU/CPU parity, which the
//! `parity_cpu` test catches.

include!(concat!(env!("OUT_DIR"), "/filters.rs"));
