//! Filter coefficients generated by `build.rs`. Re-exported as
//! crate-level `pub const` so kernels can read them at compile time.
//!
//! Phase 8j — these constants (`BINOM5`, `SSIM_WIN_1D`,
//! `SCALE_WEIGHTS`) are emitted **per crate** (one copy in iwssim's
//! `crate::filters`, one in iwssim-gpu's `crate::filters`) but the
//! emitting math lives in a single shared helper at
//! `crates/iwssim-filter-codegen/`. Both crates' `build.rs` call
//! `iwssim_filter_codegen::emit_filters_rs`, so the two copies are
//! bit-identical by construction.
//!
//! The reason both copies exist (instead of `pub use iwssim::filters::*`):
//! cube-macros that consume these constants (`lap_pyramid`, `gauss11`
//! `#[cube(launch_unchecked)]` kernels) require them to resolve through
//! the **local** crate path `crate::filters` at macro-expansion time.
//! Pulling via `iwssim::filters::*` (or a `pub use` re-export) is not
//! name-resolvable inside a `#[cube]` body — the cube codegen captures
//! `crate`-relative paths and re-emits them on the device side.

// The generated consts are now `pub(crate)` (the `filters` module is
// `pub(crate)`); a few companion scalars (`BINOM5_LEN`, `SSIM_WIN_LEN`,
// `SSIM_WIN_RADIUS`) are part of the emitted set but read only by some
// kernels, so allow dead_code for the generated block.
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/filters.rs"));
