//! Emit pyramid + Gaussian-window constants for the CPU IW-SSIM port.
//!
//! Bit-identical to `iwssim-gpu/build.rs` — the two crates MUST share
//! identical filter taps. Any drift here silently breaks parity with
//! both the GPU port AND the Python reference.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn binom5_taps() -> [f64; 5] {
    // pyrtools' `binom5` is `sqrt(2) * [1,4,6,4,1] / 16`. The sqrt(2)
    // factor is intentional: it's how pyrtools preserves L2 norm
    // through pyramid build/expand. Without it the LP coefficients
    // differ from the published Python implementation by a scale
    // factor at every level.
    let s = 2.0_f64.sqrt();
    [
        s * 1.0 / 16.0,
        s * 4.0 / 16.0,
        s * 6.0 / 16.0,
        s * 4.0 / 16.0,
        s * 1.0 / 16.0,
    ]
}

fn gaussian_1d(len: usize, sigma: f64) -> Vec<f64> {
    let half = (len as i64) / 2;
    let mut g = Vec::with_capacity(len);
    let two_s2 = 2.0 * sigma * sigma;
    for k in -half..=half {
        let x = k as f64;
        g.push((-(x * x) / two_s2).exp());
    }
    let den: f64 = g.iter().sum();
    g.iter().map(|&v| v / den).collect()
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dst = out_dir.join("filters.rs");
    let mut f = fs::File::create(&dst).expect("create filters.rs");

    writeln!(f, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(f).unwrap();

    // BINOM5 (separable 5-tap; same taps for both axes).
    let b = binom5_taps();
    writeln!(f, "pub const BINOM5_LEN: usize = 5;").unwrap();
    writeln!(f, "pub const BINOM5_RADIUS: i32 = 2;").unwrap();
    write!(f, "pub const BINOM5: [f32; 5] = [").unwrap();
    for v in b.iter() {
        write!(f, "{:.20e}_f32, ", v).unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    // SSIM 11×11 Gaussian, σ=1.5 — applied separably as 1D 11-tap.
    let g = gaussian_1d(11, 1.5);
    writeln!(f, "pub const SSIM_WIN_LEN: usize = 11;").unwrap();
    writeln!(f, "pub const SSIM_WIN_RADIUS: i32 = 5;").unwrap();
    write!(f, "pub const SSIM_WIN_1D: [f32; 11] = [").unwrap();
    for v in g.iter() {
        write!(f, "{:.20e}_f32, ", v).unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    // Per-scale MS-SSIM combination weights (β in eq 47 of Wang & Li
    // 2011) — verbatim from `iwssim.m` / `IW_SSIM_PyTorch.py`.
    writeln!(
        f,
        "pub const SCALE_WEIGHTS: [f32; 5] = [\n    \
         4.48e-2_f32, 2.856e-1_f32, 3.001e-1_f32, 2.363e-1_f32, 1.333e-1_f32,\n];"
    )
    .unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
